#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from .html import (
    html_to_text,
    probe_period,
    month_in_near_set,
    probe_fye_from_balance_asof,
    probe_fye_from_balance_window,
    probe_fye_from_text,
    fetch_html_then_txt_period,
    fetch_html_fye_month,
)
from .patterns import (
    COVER_RE,
    BAL_ASOF_RE,
    SOFP_ASOF_RE,
    COND_ASOF_RE,
    SAL_ASOF_RE,
    ASOF_PATTERNS,
    UPPER_HEAD_PATTS,
    MIX_HEAD_PATTS,
    ANCHOR_UPPER_PATTS,
    GENERIC_HEAD_PATTS,
    iter_balance_sheet_headings,
    MONTH_WORD,
    FYE_PATTS,
    PERIOD_HDR_RE,
    ACCESSION_FOLDER_RE,
    extract_dei_from_html,
)

__all__ = [
    "html_to_text",
    "probe_period",
    "month_in_near_set",
    "probe_fye_from_balance_asof",
    "probe_fye_from_balance_window",
    "probe_fye_from_text",
    "fetch_html_then_txt_period",
    "fetch_html_fye_month",
    "COVER_RE",
    "BAL_ASOF_RE",
    "SOFP_ASOF_RE",
    "COND_ASOF_RE",
    "SAL_ASOF_RE",
    "ASOF_PATTERNS",
    "UPPER_HEAD_PATTS",
    "MIX_HEAD_PATTS",
    "ANCHOR_UPPER_PATTS",
    "GENERIC_HEAD_PATTS",
    "iter_balance_sheet_headings",
    "MONTH_WORD",
    "FYE_PATTS",
    "PERIOD_HDR_RE",
    "ACCESSION_FOLDER_RE",
    "extract_dei_from_html",
]
